# Automatically generated by configure - do not modify
TARGET_ARM=y
TARGET_NAME=arm
TARGET_BASE_ARCH=arm
TARGET_ABI_DIR=arm
TARGET_XML_FILES= /root/qemu/gdb-xml/arm-core.xml /root/qemu/gdb-xml/arm-vfp.xml /root/qemu/gdb-xml/arm-vfp3.xml /root/qemu/gdb-xml/arm-neon.xml
CONFIG_SDCARD=y
CROSS_CC_GUEST="cc"
CROSS_CC_GUEST_STATIC=n
CONFIG_ARM_DIS=y
CONFIG_ARM_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
